apiVersion: stable.dwk.stable.dwk/v1
kind: DummySite
metadata:
  name: example-com
spec:
  website_url: http://example.com
  name: example-com
  image: pasiol/dummysite-scraper:latest
  succeed: false